apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        # Định nghĩa danh sách image mà Image Updater sẽ theo dõi
        argocd-image-updater.argoproj.io/image-list: "audio-web=localhost:80/lab-audio-web/audio-web"
        # Cấu hình chiến lược cập nhật cho image (dùng latest)
        argocd-image-updater.argoproj.io/audio-web.update-strategy: "latest"
  
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
