replicaCount: 1

image:
  repository: localhost:80/lab-audio-web/audio-web
  tag: "v1" 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: false  
  name: "audio-web-sa"
  automount: true
  annotations: {}

ingress:
  enabled: false  #
  className: "nginx"
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false 
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
