replicaCount: 3

image:
  repository: localhost:8089/audio-ecomweb/audio-web-reactjs
  tag: "16"
  pullPolicy: Always

service:
  type: NodePort
  port: 3000           
  targetPort: 3000     
  nodePort: 30060      

serviceAccount:
  create: false  
  name: "audio-web-sa"
  automount: true
  annotations: {}

ingress:
  enabled: false  
  className: "nginx"
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: "1"       
    memory: "1Gi" 
  limits:
    cpu: "2"       
    memory: "8Gi" 
