replicaCount: 3

image:
  repository: localhost:80/lab-audio-web/audio-web
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort
  port: 3000           
  targetPort: 3000     
  nodePort: 30060      

serviceAccount:
  create: false  
  name: "audio-web-sa"
  automount: true
  annotations: {}

ingress:
  enabled: false  
  className: "nginx"
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
